### ISSUE TITLE
refactor: rewrite site and documention

### ISSUE THREAD

**Issue by HsiangNianian** [retrofor/iamai#194]

**Comment by xadhrit** [comment]
adding english documantation (or button to translate from one lang to another. ) It's hard to understand documentation for a non-mandarin person.

**Comment by xadhrit** [comment]
let's create a task list and assign tasks!

**Comment by HsiangNianian** [comment]
> let's create a task list and assign tasks! 

good iead!

**Comment by xadhrit** [comment]
do we have to write the all pages again? Pretty messed up...

**Comment by HsiangNianian** [comment]
> do we have to write the all pages again? Pretty messed up... 

Yes, we need to rewrite all the documents, but we can refer to the previous ones, I will upload a backup of the previous documents later (a site I wrote in Vue before), so we can work a lot faster 😊💪

**Comment by HsiangNianian** [comment]
btw, I want to write a new adapter with you, I hope that iamai can adapt to discord or telegram platform (this mainly depends on which chat software you are used to, or change to fb or other such as inst software can be 🤗 ) Do you have any ideas or leads? It's easier to write a discord or telegram (especially discord) because the kook adapter is similar to discord.

**Comment by xadhrit** [comment]
> > do we have to write the all pages again? Pretty messed up...
> 
> Yes, we need to rewrite all the documents, but we can refer to the previous ones, I will upload a backup of the previous documents later (a site I wrote in Vue before), so we can work a lot faster blushmuscle

I'VE english translation of all guide pages

**Comment by xadhrit** [comment]
> btw, I want to write a new adapter with you, I hope that iamai can adapt to discord(#46) or telegram(#45) platform (this mainly depends on which chat software you are used to, or change to fb or other such as inst software can be hugs ) Do you have any ideas or leads? It's easier to write a discord or telegram (especially discord) because the kook adapter is similar to discord.

I'm looking into that. Since I'll focus more on that.

**Comment by HsiangNianian** [comment]
> > > do we have to write the all pages again? Pretty messed up...
> > 
> > Yes, we need to rewrite all the documents, but we can refer to the previous ones, I will upload a backup of the previous documents later (a site I wrote in Vue before), so we can work a lot faster blushmuscle
> 
> I'VE english translation of all guide pages

Very nice, 🤓 And we'll make a few changes. 😊
